### ISSUE TITLE
Not Working from 15th March 2020

### ISSUE THREAD

**Issue by SagarVirpara** [MrDioogo/StreamBotter#1]
Hey 

I have tested it earlier it was working but from the 15th march it is not working can you please look into it ?

**Comment by MrDioogo** [comment]
Hello, can you send me the error?

**Comment by MrDioogo** [comment]
Hello! Apparently something has changed on YouTube ... I've tried to solve it and I can't, I'm sorry

**Comment by SagarVirpara** [comment]
@MrDioogo Yeah! I debuged it but no luck yet.

I am working on the solution. If I will find any solution then I will definitely let you know.

**Comment by MrDioogo** [comment]
Ok, thank you.

**Comment by SagarVirpara** [comment]
@MrDioogo  Can you explain me what url2 variable does ?

**Comment by MrDioogo** [comment]
I honestly don't remember xD

**Comment by MrDioogo** [comment]
`url2 = "https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage&cpn=AiWtf2fjIwVS2MeQ&docid=" + token + "&ver=2&cmt=7926.045&ei=igGSXce3IM2NgAfasp-ABg&fmt=133&fs=0&rt=1096.007&of=L_224b5BokWsQ5UWgAws_w&euri&lact=2837&live=dvr&cl=271684942&state=playing&vm=CAEQABgEKhhJc0gwZ2w0QmFfbTBWSXlWNm9ITmRRPT0&volume=100&c=MWEB&cver=2.20190928.07.00&cplayer=UNIPLAYER&cbrand=apple&cbr=Safari%20Mobile&cbrver=12.1.15E148&cmodel=iphone&cos=iPhone&cosver=12_2&cplatform%20=MOBILE&delay=5&hl=ru_RU&cr=DE&rtn=1396&afmt=140&lio=1556394045.182&idpj=&ldpj=&rti=1096&muted=0&st=7626.045&et=7926.045 "`

**Comment by SagarVirpara** [comment]
Yes. What is the use of that url ?

**Comment by MrDioogo** [comment]
For send the viewers.

**Comment by SagarVirpara** [comment]
From where did you get it ?
Seems like there is some problem I guess.

**Comment by MrDioogo** [comment]
I don't rly know anymore...

**Comment by MrDioogo** [comment]
I fixed it and I created a new release: https://github.com/MrDioogo/StreamBotter/releases/tag/1.0.1

**Comment by SagarVirpara** [comment]
Ohh nice it works

**Comment by SagarVirpara** [comment]
Updates by owner and it is working
